-- Run this once in Supabase Dashboard -> SQL Editor.

create table if not exists public.shows (
    show_id text primary key,
    movie_name text not null,
    show_time text not null,
    total_rows integer not null check (total_rows between 1 and 15),
    total_cols integer not null check (total_cols between 1 and 15),
    ticket_price integer not null check (ticket_price > 0),
    poster_color text not null default '#1f6fb2',
    created_at timestamptz not null default now()
);

create table if not exists public.bookings (
    ticket_no bigint generated by default as identity (start with 1001) primary key,
    show_id text not null references public.shows(show_id) on delete restrict,
    movie_name text not null,
    show_time text not null,
    customer_name text not null,
    phone text not null,
    seat_labels text not null,
    total_price integer not null check (total_price > 0),
    created_at timestamptz not null default now()
);

create table if not exists public.booking_seats (
    show_id text not null references public.shows(show_id) on delete cascade,
    seat_label text not null,
    ticket_no bigint not null references public.bookings(ticket_no) on delete cascade,
    primary key (show_id, seat_label)
);

create or replace function public.create_booking(
    p_show_id text,
    p_customer_name text,
    p_phone text,
    p_seat_labels text[],
    p_price_per_seat integer
)
returns jsonb
language plpgsql
as $$
declare
    selected_show public.shows;
    created_booking public.bookings;
    seat_label text;
begin
    select * into selected_show from public.shows where show_id = p_show_id;
    if not found then
        return jsonb_build_object('ok', false, 'message', 'Show not found.');
    end if;
    if coalesce(array_length(p_seat_labels, 1), 0) = 0 then
        return jsonb_build_object('ok', false, 'message', 'Please select at least one seat.');
    end if;
    if array_length(p_seat_labels, 1) <> (select count(distinct value) from unnest(p_seat_labels) as value) then
        return jsonb_build_object('ok', false, 'message', 'Duplicate seats were selected.');
    end if;
    foreach seat_label in array p_seat_labels loop
        if seat_label !~ '^[A-O]([0-9]|1[0-4])$'
           or ascii(left(seat_label, 1)) - ascii('A') >= selected_show.total_rows
           or substring(seat_label from 2)::integer >= selected_show.total_cols then
            return jsonb_build_object('ok', false, 'message', 'One or more selected seats are invalid.');
        end if;
    end loop;

    begin
        insert into public.bookings (
            show_id, movie_name, show_time, customer_name, phone, seat_labels, total_price
        ) values (
            selected_show.show_id, selected_show.movie_name, selected_show.show_time,
            p_customer_name, p_phone, array_to_string(p_seat_labels, ', '),
            array_length(p_seat_labels, 1) * p_price_per_seat
        ) returning * into created_booking;

        insert into public.booking_seats (show_id, seat_label, ticket_no)
        select p_show_id, value, created_booking.ticket_no from unnest(p_seat_labels) as value;
    exception when unique_violation then
        return jsonb_build_object('ok', false, 'message', 'One or more seats were just booked. Please choose another seat.');
    end;

    return jsonb_build_object('ok', true, 'booking', to_jsonb(created_booking));
end;
$$;

insert into public.shows (show_id, movie_name, show_time, total_rows, total_cols, ticket_price, poster_color)
values
    ('abc', 'Finding Nemo', '03:50 PM', 5, 8, 150, '#1f6fb2'),
    ('asd', 'Ice Age', '10:00 AM', 5, 8, 150, '#2a9d8f'),
    ('bcd', 'Avatar', '05:00 PM', 5, 8, 200, '#6a4c93')
on conflict (show_id) do nothing;